-- DEMO SEED DATA REMOVED
--
-- This migration is intentionally a no-op. The previous demo customer/site/
-- asset/job rows were removed so new database resets do not re-create sample
-- operational data.
--
-- To clear an existing database deliberately, run:
--   scripts/clear-app-data.sql
